# Generated by Django 5.0.4 on 2024-04-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0002_rename_userprofile_userprofilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='registered_date',
        ),
    ]
